# #18470 Calls to stash() inside of persist callbacks should throw exception
ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.persistence.Eventsourced.akka$persistence$Eventsourced$$super$stash")
